### ISSUE TITLE
Walnut Application Hosting

### ISSUE THREAD

**Issue by jeor0980** [CuBoulder/walnut#1]
We need to figure out where Walnut will live and thrive. 

Possibilities:

- AWS
- Google Cloud 
- Linode
- Digital Ocean
- Heroku

Stack requirements:

- Linux (Ubuntu LTS or CentOS)
- Python 3.7, PHP 7, node.js 12
- WSGI or GNUnicorn or UWSGI
- Apache or nginx

State:
- Mongo

Current plans are to keep all in one virtual machine

**Comment by jwfuller** [comment]
https://flask.palletsprojects.com/en/1.1.x/deploying/

**Comment by jwfuller** [comment]
Based on conversations with Pantheon and others, I lean towards GCP over AWS.
