### ISSUE TITLE
Redis logic in settings.php

### ISSUE THREAD

**Issue by jeor0980** [CuBoulder/walnut#11]
Some sites will have redis but most will not, the [code detailed here](https://github.com/CuBoulder/express-mono-upstream/wiki/Steps-to-Enable-redis-on-express-sites) needs to be added to sites with redis enabled.

**Comment by jwfuller** [comment]
Issue moved to [CuBoulder/express-mono-upstream #23](https://github.com/CuBoulder/express-mono-upstream/issues/23) via [**ZenHub**](https://www.zenhub.com/)
