### ISSUE TITLE
Investigate rate limiting in terminus

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/walnut#23]
Any rakes we need to avoid?

**Comment by jeor0980** [comment]
After opening a ticket with Pantheon Support, there appear to be no limits on Terminus calls but we can contact support in the unlikely event we hit a limit.

[Pantheon Ticket](https://dashboard.pantheon.io/organizations/81be1591-5c06-4339-827f-d9a3605288be#support/ticket/448355)
