### ISSUE TITLE
Application Monitoring and Alerting

### ISSUE THREAD

**Issue by jeor0980** [CuBoulder/walnut#5]
Some of our Pantheon instances will have New Relic, we can leverage that to help with monitoring of some of our critical sites, but what about the rest?

Current Monitoring:
- New Relic
- Nagios
- Pingdom

Do we continue to use our current alerting tools?
- Pagerduty

Potential New Monitoring Tools:
- prometheus

**Comment by jwfuller** [comment]
Closed for https://github.com/CuBoulder/baseline/issues/48
