### ISSUE TITLE
Deploy inital commit of repo to GCP

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/walnut#8]
Use the evaluate GCP as a host and to make sure that rapid prototyping is easy.

**Comment by tirazel** [comment]
Initial test deployment on GCP was successful using CentOS 7.  8.0 has been released, though official cloud provider images (AWS/GCP/etc) have not yet been created.

**Comment by tirazel** [comment]
Opened a pull request to add the needed files for uWSGI operation, and updated the README.md with new instructions
